# Generated by Django 4.2.13 on 2024-05-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripanalysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrineStripImage',
        ),
    ]
